### ISSUE TITLE
Create Car

### ISSUE THREAD

**Issue by mir-jalal** [Stackeduary/Enterprise-System-Integration-2022#2]
We need to store Cars for our application.

**Acceptance Criteria**:
* [ ] #3
  - id: Integer
  - licensePlateNumber: String
  - brand: String
  - model: String
  - year: Integer
  - currentMarketValue: BigDecimal
  - Mileage: BigDecimal
  - customer: Customer
  - pickUpLocation: PickUpLocation:
    + latitude
    + longitude
* [ ] Create `CarEntry` entity with `availability: boolean` and `car: Car` parameters
* [ ] Create `CarController` with following URLs:
  - `/cars/create` : POST
  - `/cars/get/{carId}`: GET
  - `/cars/delete/{carId}`: DELETE
  - `/cars/update/{carId}`: PUT
  - `/cars`: GET
* [ ] Create `CarService` with required business logic methods
* [ ] Create `CarRepository` with required query methods

**Comment by neverwriter** [comment]
Hello, is creating Customer and PickUpLocation class also part of this task?
